export const LISTA_ARTISTAS = [
  "milionario-e-jose-rico",
  "trio-parada-dura",
  "tonico-e-tinoco",
  "zeze-di-camargo-e-luciano",
  "chitaozinho-e-xororo",
  "leandro-leonardo",
  "leonardo",
  "bruno-e-marrone",
  "gian-e-giovani",
  "almir-sater",
  "daniel",
  "sergio-reis",
  "victor-leo",
  "luan-santana",
  "gusttavo-lima",
  "guilherme-e-benutto",
  "marilia-mendonca",
  "maiara-e-maraisa",
  "marcos-e-belutti",
  "michel-telo",
  "henrique-e-juliano",
  "jorge-mateus",
  "joao-bosco-e-vinicius",
  "legiao-urbana",
  "reacao-em-cadeia",
  "cidadao-quem",
  "skank",
  "frejat",
  "engenheiros-do-havai",
];

export const ESTILOS = {
  "Sertanejo Raiz": [
    "milionario-e-jose-rico",
    "trio-parada-dura",
    "tonico-e-tinoco",
  ],
  Sertanejo: [
    "zeze-di-camargo-e-luciano",
    "chitaozinho-e-xororo",
    "leandro-leonardo",
    "leonardo",
    "bruno-e-marrone",
    "gian-e-giovani",
    "almir-sater",
    "daniel",
    "sergio-reis",
    "victor-leo",
    "luan-santana",
    "gusttavo-lima",
    "guilherme-e-benutto",
    "marilia-mendonca",
    "maiara-e-maraisa",
    "marcos-e-belutti",
    "michel-telo",
    "henrique-e-juliano",
    "jorge-mateus",
    "joao-bosco-e-vinicius",
  ],
  "Pop Rock": [
    "cidadao-quem", 
    "skank", 
    "frejat", 
    "engenheiros-do-hawaii"],
};

export const SEARCH_SONGS_API = "https://studiosolsolr-a.akamaihd.net/cc/h2/";
export const CIFRACLUB_SONG_ID = "2";
export const CIFRACLUB_URL = "https://www.cifraclub.com.br";
export const VAGALUME_URL = "https://www.vagalume.com.br";
